package worktree

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/bklimov-web/wt-cli/internal/git"
	"github.com/bklimov-web/wt-cli/internal/installer"
)

// envFileHints are substrings (matched case-insensitively against a
// gitignored file's base name) that mark it as local config worth copying
// into a new worktree, as opposed to build output or other ignored cruft.
var envFileHints = []string{"env", "local", "secret"}

// Init scaffolds a .wt.toml in mainDir: an install_commands line if
// installer.Suggest detects one, and an env_files line for any gitignored
// file whose name looks like local config (see envFileHints) — these are
// exactly the files a new worktree won't get from git itself. It refuses
// to overwrite an existing .wt.toml, and fails if nothing was detected
// (the defaults already fit). Status messages are written to w.
func Init(mainDir string, w io.Writer) error {
	path := filepath.Join(mainDir, ".wt.toml")
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s already exists", path)
	}

	var lines []string

	if cmds := installer.Suggest(mainDir); len(cmds) > 0 {
		lines = append(lines, "install_commands = "+tomlStrings(cmds))
		fmt.Fprintf(w, "wt: detected install step: %s\n", strings.Join(cmds, " && "))
	}

	envFiles, err := suggestEnvFiles(mainDir)
	if err != nil {
		return err
	}
	if len(envFiles) > 0 {
		lines = append(lines, "env_files = "+tomlStrings(envFiles))
		fmt.Fprintf(w, "wt: detected env files: %s\n", strings.Join(envFiles, ", "))
	}

	if len(lines) == 0 {
		return fmt.Errorf("nothing to configure: no install step or env files detected — defaults already fit")
	}

	content := "# Generated by `wt init` — edit freely.\n" + strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}

	fmt.Fprintf(w, "wt: wrote %s\n", path)
	return nil
}

// suggestEnvFiles returns mainDir's gitignored files whose name matches
// envFileHints.
func suggestEnvFiles(mainDir string) ([]string, error) {
	ignored, err := git.IgnoredFiles(mainDir)
	if err != nil {
		return nil, err
	}

	var found []string
	for _, f := range ignored {
		name := strings.ToLower(filepath.Base(f))
		for _, hint := range envFileHints {
			if strings.Contains(name, hint) {
				found = append(found, f)
				break
			}
		}
	}
	return found, nil
}

// tomlStrings renders items as a TOML array of strings, e.g. ["a", "b"].
func tomlStrings(items []string) string {
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = strconv.Quote(it)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
